ci:
    skip: [ruff]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]

      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: local
    hooks:
      - id: pixi-update
        name: pixi update
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && pixi update && git add pixi.lock'
        language: system
        files: ^pyproject\.toml$
        types: [text]
