ci:
    skip: [ruff, pixi-update-default, pixi-update-cpu, pixi-update-gpu]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]

      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.2.0
    hooks:
      - id: shell-fmt-go
        args:
          - --write
          - --simplify
          - --indent
          - "2"

  - repo: local
    hooks:
      - id: pixi-update-default
        name: pixi update default
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && pixi update && git add pixi.lock'
        language: system
        files: ^pyproject\.toml$
        types: [text]

      - id: pixi-update-cpu
        name: pixi update cpu
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && pixi update -e cpu && git add pixi.lock'
        language: system
        files: ^pyproject\.toml$
        types: [text]

      - id: pixi-update-gpu
        name: pixi update gpu
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && pixi update -e gpu && git add pixi.lock'
        language: system
        files: ^pyproject\.toml$
        types: [text]

  - repo: local
    hooks:
      - id: gcp-sh-test
        name: gcp.sh tests
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && cd scripts && ./test-gcp.sh'
        language: system
        files: .*gcp.*\.sh$
        types: [executable]
