ci:
    skip: [pixi-install-default, pixi-install-cpu, pixi-install-gpu]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]

      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.2.0
    hooks:
      - id: shell-fmt-go
        args:
          - --write
          - --simplify
          - --indent
          - "2"

  - repo: local
    hooks:
      - id: pixi-install-default
        name: pixi install (solving default)
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && pixi install --locked -e default'
        language: system
        files: ^pyproject\.toml$
        types: [text]

      - id: pixi-install-cpu
        name: pixi install (solving cpu)
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && pixi install --locked -e cpu'
        language: system
        files: ^pyproject\.toml$
        types: [text]

      - id: pixi-install-gpu
        name: pixi install (solving gpu)
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && pixi install --locked -e gpu'
        language: system
        files: ^pyproject\.toml$
        types: [text]

  - repo: local
    hooks:
      - id: gcp-sh-test
        name: gcp.sh tests
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && cd scripts && ./test-gcp.sh'
        language: system
        files: .*gcp.*\.sh$
        types: [executable]

      - id: pytest-sh-test
        name: pytest.sh tests
        entry: bash -c 'cd $(git rev-parse --show-toplevel) && cd scripts && ./test-pytest.sh'
        language: system
        files: .*pytest.*\.sh$
        types: [executable]
