# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import flatbuffers

class FBColorDict(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBColorDict(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBColorDict()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def FBColorDictBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x63\x64\x69\x63", size_prefixed=size_prefixed)

    # FBColorDict
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBColorDict
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBKeyValuePair import FBKeyValuePair
            obj = FBKeyValuePair()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBColorDict
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def FBColorDictStart(builder): builder.StartObject(1)
def FBColorDictAddEntries(builder, entries): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)
def FBColorDictStartEntriesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FBColorDictEnd(builder): return builder.EndObject()
