# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import flatbuffers

class FBKeypointsAssignment(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBKeypointsAssignment(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBKeypointsAssignment()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def FBKeypointsAssignmentBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x6B\x65\x79\x61", size_prefixed=size_prefixed)

    # FBKeypointsAssignment
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBKeypointsAssignment
    def ObjectAssignments(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # FBKeypointsAssignment
    def ObjectAssignmentsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # FBKeypointsAssignment
    def ObjectAssignmentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def FBKeypointsAssignmentStart(builder): builder.StartObject(1)
def FBKeypointsAssignmentAddObjectAssignments(builder, objectAssignments): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objectAssignments), 0)
def FBKeypointsAssignmentStartObjectAssignmentsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FBKeypointsAssignmentEnd(builder): return builder.EndObject()
