name: Codebase tests (GPU) 

on:
  pull_request:
  push:
    branches:
      - eighty-devx-gpu-ci

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  XLA_FLAGS: --xla_gpu_enable_command_buffer=
  XLA_PYTHON_CLIENT_PREALLOCATE: "false"
  XLA_PYTHON_CLIENT_ALLOCATOR: "platform"

jobs:
  test:
    strategy:
      matrix:
        runner: [ParallelHoss]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install nvdiffrast dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglvnd0 libgl1 libglx0 libegl1 libgles2 libglvnd-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libnvidia-gl-535 mesa-common-dev libegl1-mesa-dev libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev ffmpeg
          version: 1.0

      # - name: Setup asset caching
      #   id: cache-assets
      #   uses: actions/cache@v4
      #   with:
      #     path: assets
      #     key: ${{ runner.os }}-${{ matrix.runner }}-assets
      #     restore-keys: ${{ runner.os }}-${{ matrix.runner }}-assets

      # - name: Setup pixi caching
      #   id: cache-pixi
      #   uses: actions/cache@v4
      #   with:
      #     path: .pixi
      #     key: ${{ runner.os }}-${{ matrix.runner }}-pixi
      #     restore-keys: ${{ runner.os }}-${{ matrix.runner }}-pixi

      # - name: System debugging
      #   run: |
      #     nvidia-smi
      #     ldconfig -p | grep EGL
      #     ldconfig -p | grep GL
      #     ls -la /usr/share/glvnd/
      #     ls -la /usr/share/glvnd/egl_vendor.d/
      #     cat /usr/share/glvnd/egl_vendor.d/50_mesa.json
      #     sudo find / -name "*nvidia.so*"
      #     sudo find / -name "*nvidia*"

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.ARTIFACT_REGISTRY_KEY }}"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install system environment and project dependencies
        env:
          GITHUB_CI: "true"
          #LD_LIBRARY_PATH: "/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
        run: |
          ./install.sh
          source ~/.bashrc
          export PATH="/home/runner/.pixi/bin:/home/runner/.local/bin:$PATH"
          export CPLUS_INCLUDE_PATH="$GITHUB_WORKSPACE/.pixi/envs/default/targets/x86_64-linux/include"
          pixi tree
          export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu
          env
          pixi run -vv test-ci



      # - name: Run tests
      #   env:
      #     PATH: "/home/runner/.pixi/bin:/home/runner/.local/bin:$PATH"
      #     CONDA_PREFIX: "/home/runner/.pixi/envs/default"
      #   run: pixi run all-tests-ci

      # - name: Run tests
      #   uses: prefix-dev/setup-pixi@v0.8.1
      #   env:
      #     PATH: "/home/runner/.pixi/bin:/home/runner/.local/bin:$PATH"
      #     RUNNER_DEBUG: true
      #   with:
      #     pixi-version: v0.25.0
      #     activate-environment: true
      #     cache: true
      # - run: |
      #     ls -la .pixi/envs/default
          #cp assets/system/libEGL.so .pixi/envs/default/x86_64-conda-linux-gnu/sysroot/usr/lib64/
          #pixi run test
