name: pdoc

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.ARTIFACT_REGISTRY_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: pixi run docs
        run: |
          # install pixi
          curl -fsSL https://pixi.sh/install.sh | bash
          export PATH=/home/runner/.pixi/bin:$PATH

          # install pipx and inject gcp backend
          pixi global install pipx
          pipx install keyring
          pipx inject keyring \
          keyrings.google-artifactregistry-auth \
            --index-url \
            https://pypi.org/simple

          # render docs
          pixi run docs

      - name: Create website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./docs/render

  publish:
    needs: build-deploy
    uses: probcomp/gen-website-private/.github/workflows/publish_private_website.yml@main
    with:
      artifact: website
