name: pixi

on:
  pull_request:
  push:
    branches:
      - eightysteele/spnup-14-pypi-authentication-broken-on-gcp

jobs:
  pixi-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.ARTIFACT_REGISTRY_KEY }}"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: pixi install locked
        run: |
          # install pixi
          curl -fsSL https://pixi.sh/install.sh | bash
          export PATH=/home/runner/.pixi/bin:/home/runner/.local/bin:$PATH
          source ~/.bashrc

          # install pipx and inject gcp backend
          pixi global install pipx
          pipx install --force keyring==25.3.0
          pipx inject keyring \
            keyrings.google-artifactregistry-auth \
            --index-url \
            https://pypi.org/simple \
            --force

          # ensure all deps across all environments and platforms are solving
          pixi --version
          pixi clean && pixi clean cache -y
          pixi install --locked -e default -v --pypi-keyring-provider subprocess
          pixi install --locked -e cpu -v --pypi-keyring-provider subprocess
          pixi install --locked -e gpu -v --pypi-keyring-provider subprocess
