name: Codebase tests (GPU)

on:
  pull_request:
  push:
    branches:
      - eightysteele/gen-521-setup-custom-github-runner-on-gcp

  workflow_dispatch:

env:
  XLA_PYTHON_CLIENT_PREALLOCATE: "false"
  XLA_PYTHON_CLIENT_ALLOCATOR: "platform"

jobs:
  test:
    runs-on: [self-hosted, b3d]
    steps:
      - uses: actions/checkout@v4

      - name: install curl
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: curl
          version: 1.0

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.ARTIFACT_REGISTRY_KEY }}"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # - name: ssh
      #   uses: ryanchapman/gha-ssh@v1
      #   timeout-minutes: 20
      #   with:
      #     authorized_github_users: 'eightysteele'
      #     debug: true

      - name: Run pixi test
        run: |
          # install pixi
          curl -fsSL https://pixi.sh/install.sh | bash
          source ~/.bashrc
          export PATH=$HOME/.pixi/bin:$HOME/.local/bin:$PATH

          # install pipx and inject gcp backend
          pixi global install pipx
          pipx install keyring
          pipx inject keyring \
            keyrings.google-artifactregistry-auth \
            --index-url \
            https://pypi.org/simple

          # install gpu environment
          pixi clean && pixi clean cache --yes
          pixi install --locked -e gpu -v --pypi-keyring-provider subprocess

          # run test
          # pixi run -e gpu test
          # pixi run -e gpu python -m pytest tests/test_render_ycb_model.py::test_renderer_full
          # pixi run -e gpu gpu-test
          pixi run -e gpu gpu-test-2
