name: Ruff linter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11.5

    - uses: chartboost/ruff-action@v1
      with:
        version: 0.5.4
        args: check --output-format github
